### ISSUE TITLE
DUH support

### ISSUE THREAD

**Issue by drom** [rggen/rggen-duh#1]
Great project.
We are developing a new format named DUH. It can capture register information.
Would you be interested in adding D∪H format support?

## more info

* https://github.com/sifive/duh
* https://github.com/sifive/duh-schema/blob/master/lib/register.js
* https://github.com/sifive/block-pio-sifive/blob/master/docs/pio.json5#L94

**Comment by taichi-ishitani** [comment]
@drom ,

I have an additional question.

In the above PIO example, `csrMemMap` is used to describe register map but I found `memoryMap` but not `csrMemMap` from the duh-schema.
Is `csrMemMap` valid keyword?

**Comment by taichi-ishitani** [comment]
> https://github.com/sifive/duh/blob/master/docs/component.md#registers
> In this example `memoryMaps` is a member of `component`.
> https://github.com/sifive/block-pio-sifive/blob/master/docs/pio.json5
> But in this example, it is a member of `definition`.
> What is different between these `memoryMaps`.

This is resolved by myself.
`csrMemMap` witnin `definition` is referred from `memoryMaps` within `component`.

**Comment by taichi-ishitani** [comment]
@drom ,

What do `modify` value of `modifiedWriteValue` and `modify` value of `readAction` mean?

* https://github.com/sifive/duh-schema/blob/86e26211117b514b18d006cbd0d6c4fe1931bee3/lib/field.js#L17
* https://github.com/sifive/duh-schema/blob/86e26211117b514b18d006cbd0d6c4fe1931bee3/lib/field.js#L26

**Comment by taichi-ishitani** [comment]
Default value of access/modifiedWriteValue/ReadAction:
sifive/duh#80

**Comment by taichi-ishitani** [comment]
| RgGen bit field type | Support? | access         | modifiedWriteValue | readAction    | resetValue    | reserved |
|:---------------------|:---------|:---------------|:-------------------|:--------------|:--------------|:---------|
| rw                   | yes      | read-write     | not specified      | not specified | don't care    | no       |
| ro                   | yes      | read-only      | don't care         | not specified | not specified | no       |
| rof                  | yes      | read-only      | don't care         | not specified | specified     | no       |
| wo                   | yes      | write-only     | not specified      | don't care    | don't care    | no       |
| rc                   | yes      | read-only      | don't care         | clear         | don't care    | no       |
| w0c                  | yes      | read-write     | zeroToClear        | not specified | don't care    | no       |
| w1c                  | yes      | read-write     | oneToClear         | not specified | don't care    | no       |
| rs                   | yes      | read-only      | don't care         | set           | don't care    | no       |
| w0s                  | yes      | read-write     | zeroToSet          | not specified | don't care    | no       |
| w1s                  | yes      | read-write     | oneToSet           | not specified | don't care    | no       |
| rwc                  | no       |                |                    |               |               |          |
| rwe                  | no       |                |                    |               |               |          |
| rwl                  | no       |                |                    |               |               |          |
| rws                  | no       |                |                    |               |               |          |
| w0crs                | yes      | read-write     | zeroToClear        | set           | don't care    | no       |
| w1crs                | yes      | read-write     | oneToClear         | set           | don't care    | no       |
| w0src                | yes      | read-write     | zeroToSet          | clear         | don't care    | no       |
| w1src                | yes      | read-write     | oneToSet           | clear         | don't care    | no       |
| w0trg                | no       |                |                    |               |               |          |
| w1trg                | no       |                |                    |               |               |          |
| w1                   | yes      | read-writeOnce | not specified      | not specified | don't care    | no       |
| wo1                  | yes      | writeOnce      | not specified      | don't care    | don't care    | no       |
| reserved             | yes      | don't care     | don't care         | don't care    | don't care    | yes      |

**Comment by taichi-ishitani** [comment]
Version 0.1.0 is just released.

**Comment by taichi-ishitani** [comment]
Hi @drom ,

I just released initial version of DUH plugin for RgGen.
If you have enough time, can you try to use?
